services:
  users-service:
    build: ./src/services/users/
    image: users-service
    ports:
      - "8080:80"
    networks:
      - app-network
  tasks-service:
    build: ./src/services/tasks/
    image: tasks-service
    ports:
      - "8081:80"
    networks:
      - app-network
  graphql-gateway:
    build: ./src/services/gateway/
    image: graphql-gateway
    ports:
      - "8082:4000"
    depends_on:
      - users-service
      - tasks-service
    networks:
      - app-network
networks:
  app-network:
    driver: bridge